[build]
  publish = "."
  command = "echo 'Static site - no build required'"
  base = "."

[build.processing]
  skip_processing = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://pagead2.googlesyndication.com https://cors-anywhere.herokuapp.com https://unpkg.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com https://unpkg.com; font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://cors-anywhere.herokuapp.com https://hasanadiguzel.com.tr;"

[[redirects]]
  from = "/api/*"
  to = "https://hasanadiguzel.com.tr/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[build.environment]
  NODE_VERSION = "18"